using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using KarateSchool.Web.Models.Interfaces;

namespace KarateSchool.Web.Models.Entities;

public class Administrator : User, IReportable
{
    public string AccessLevel { get; private set; } = string.Empty;

    /// <summary>Alias for UserId to match the UML attribute name; same physical key (TPT).</summary>
    [NotMapped]
    public int AdminId => UserId;

    private readonly List<Announcement> _announcements = new();

    public IReadOnlyCollection<Announcement> Announcements => _announcements;

    private Administrator()
    {
    }

    public Administrator(
        string fullName,
        string email,
        string passwordHash,
        string phone,
        string accessLevel)
        : base(fullName, email, passwordHash, phone, "Administrator")
    {
        SetAccessLevel(accessLevel);
    }

    public void SetAccessLevel(string accessLevel)
    {
        if (string.IsNullOrWhiteSpace(accessLevel))
            throw new ArgumentException("Access level is required.", nameof(accessLevel));
        AccessLevel = accessLevel.Trim();
    }

    public Announcement PostAnnouncement(string title, string content, DateTime datePosted)
    {
        var announcement = new Announcement(this, title, content, datePosted);
        _announcements.Add(announcement);
        return announcement;
    }

    public string GenerateReport()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Administrator Report generated by {FullName} on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine($"Access level: {AccessLevel}");
        sb.AppendLine($"Announcements posted: {_announcements.Count}");
        return sb.ToString();
    }

    public override string ToString() => $"{base.ToString()} | Access: {AccessLevel}";
}
